plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.vocabapplock'
version = '1.0.0'

android {
  namespace 'expo.modules.vocabapplock'
  compileSdkVersion rootProject.ext.compileSdkVersion

  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
  }
}

dependencies {
  implementation project(':expo-modules-core')
}
