import { useEffect, useState } from 'react';
import { ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Deck, getDecks } from '@/db/queries';

const c = { blue: '#4255ff', ink: '#1f2943', muted: '#66728f', canvas: '#f6f7fb', border: '#dfe3ee', white: '#fff', pale: '#e9ebff' };
export default function ExploreScreen() { const [decks, setDecks] = useState<Deck[]>([]); useEffect(() => setDecks(getDecks()), []); const cards = decks.reduce((sum, deck) => sum + (deck.card_count ?? 0), 0); const largest = [...decks].sort((a,b) => (b.card_count ?? 0)-(a.card_count ?? 0))[0]; return <SafeAreaView style={s.screen} edges={['top']}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>學習總覽</Text><Text style={s.title}>你的進度</Text><View style={s.hero}><Text style={s.number}>{cards}</Text><Text style={s.heroLabel}>張可複習的詞卡</Text><View style={s.line}/><Text style={s.note}>{decks.length ? '從一份單字本開始，持續累積。' : '建立一份單字本，開始累積你的詞卡。'}</Text></View><Text style={s.section}>本週學習</Text><View style={s.row}><Stat value={String(decks.length)} label="單字本"/><Stat value={String(cards)} label="詞卡"/></View><Text style={s.section}>下一步</Text><View style={s.next}><View style={s.badge}><Text style={s.badgeText}>01</Text></View><View style={{flex:1}}><Text style={s.nextTitle}>{largest ? `複習「${largest.title}」` : '建立你的第一份單字本'}</Text><Text style={s.nextBody}>{largest ? `${largest.card_count ?? 0} 張詞卡等待你複習。` : '先新增一份單字本，再放入想記住的單字。'}</Text></View></View></ScrollView></SafeAreaView>; }
function Stat({value,label}:{value:string;label:string}) { return <View style={s.stat}><Text style={s.statValue}>{value}</Text><Text style={s.statLabel}>{label}</Text></View>; }
const s=StyleSheet.create({screen:{flex:1,backgroundColor:c.canvas},content:{padding:20,paddingBottom:110},eyebrow:{color:c.muted,fontSize:13,fontWeight:'800'},title:{color:c.ink,fontSize:30,fontWeight:'800',marginTop:4,marginBottom:22},hero:{padding:24,backgroundColor:c.blue,borderRadius:8,borderBottomWidth:4,borderBottomColor:'#2f3fca'},number:{color:c.white,fontSize:42,fontWeight:'800'},heroLabel:{color:'#e8ebff',fontSize:15,fontWeight:'700',marginTop:2},line:{height:1,backgroundColor:'#7380ff',marginVertical:18},note:{color:c.white,fontSize:14,lineHeight:21},section:{color:c.ink,fontSize:18,fontWeight:'800',marginTop:30,marginBottom:12},row:{flexDirection:'row',gap:12},stat:{flex:1,padding:18,backgroundColor:c.white,borderWidth:1,borderColor:c.border,borderRadius:8},statValue:{color:c.ink,fontSize:25,fontWeight:'800'},statLabel:{color:c.muted,fontSize:13,marginTop:4},next:{flexDirection:'row',padding:18,backgroundColor:c.white,borderWidth:1,borderColor:c.border,borderRadius:8},badge:{width:38,height:38,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:c.pale,marginRight:14},badgeText:{color:c.blue,fontSize:12,fontWeight:'800'},nextTitle:{color:c.ink,fontSize:16,fontWeight:'800'},nextBody:{color:c.muted,fontSize:14,lineHeight:20,marginTop:5}});
