import { useEffect, useState } from 'react';
import { Alert, Platform, ScrollView, StatusBar, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { VocabAppLock } from 'vocab-app-lock';
import { getCardsByDeckId, getDecks } from '@/db/queries';
import { initDatabase } from '@/db/schema';

const c = { blue:'#4255ff', blueDark:'#2f3fca', ink:'#1f2943', muted:'#66728f', canvas:'#f6f7fb', border:'#dfe3ee', white:'#fff', pale:'#e9ebff' };
const suggestedApps = [{ label:'Instagram', id:'com.instagram.android' }, { label:'YouTube', id:'com.google.android.youtube' }, { label:'Facebook', id:'com.facebook.katana' }, { label:'TikTok', id:'com.zhiliaoapp.musically' }];

export default function SettingsScreen() {
  const [enabled, setEnabled] = useState(false); const [selected, setSelected] = useState<string[]>([]); const [custom, setCustom] = useState(''); const [cooldown, setCooldown] = useState(15); const [status, setStatus] = useState(false); const [question, setQuestion] = useState<{prompt:string;answer:string} | null>(null);
  useEffect(() => { initDatabase(); const deck = getDecks()[0]; const card = deck ? getCardsByDeckId(deck.id)[0] : undefined; if (card) setQuestion({ prompt: card.definition, answer: card.word }); if (Platform.OS === 'android') setStatus(VocabAppLock?.getStatus().serviceEnabled ?? false); }, []);
  const save = () => { if (!question) return Alert.alert('需要詞卡', '請先建立至少一張詞卡，App Lock 才能出題。'); const targets = [...selected, ...custom.split(',').map(x=>x.trim()).filter(Boolean)]; if (!targets.length) return Alert.alert('選擇受限 App', '請至少選擇一個 App 或填入套件名稱。'); if (!VocabAppLock) return Alert.alert('需要 Android development build', 'App Lock 不支援 Expo Go、iOS 或 Web。請重新建置 Android development build。'); VocabAppLock.setConfig({ packageNames: targets, cooldownMinutes: cooldown, prompt: question.prompt, answer: question.answer }); setEnabled(true); Alert.alert('已儲存', '設定已寫入 App Lock 服務。'); };
  const openAccessibility = () => { if (!VocabAppLock) return Alert.alert('需要 Android development build', '請在已重建的 Android App 中開啟此設定。'); VocabAppLock.openAccessibilitySettings(); };
  return <SafeAreaView style={s.screen} edges={['top']}><StatusBar barStyle="dark-content"/><ScrollView contentContainerStyle={s.content}><Text style={s.eyebrow}>設定</Text><Text style={s.title}>應用程式鎖</Text><View style={s.hero}><View style={s.heroCopy}><Text style={s.heroTitle}>先背一個單字</Text><Text style={s.heroText}>開啟受限 App 時，答對填空題才會解除鎖定。</Text></View><Switch value={enabled} onValueChange={setEnabled} trackColor={{false:'#dfe3ee',true:'#8e99ff'}} thumbColor={enabled?c.blue:'#fff'}/></View><Text style={s.section}>受限 App</Text>{suggestedApps.map(app => <TouchableOpacity key={app.id} onPress={() => setSelected(v => v.includes(app.id) ? v.filter(x=>x!==app.id) : [...v,app.id])} style={s.appRow}><View style={[s.checkbox,selected.includes(app.id)&&s.checked]}>{selected.includes(app.id)&&<Text style={s.tick}>✓</Text>}</View><View><Text style={s.appName}>{app.label}</Text><Text style={s.package}>{app.id}</Text></View></TouchableOpacity>)}<Text style={s.fieldLabel}>其他 App 套件名稱（以逗號分隔）</Text><TextInput value={custom} onChangeText={setCustom} placeholder="例如：com.example.game" placeholderTextColor="#8a94ad" style={s.input}/><Text style={s.section}>答對後的緩衝時間</Text><View style={s.cooldowns}>{[5,15,30].map(value=><TouchableOpacity key={value} onPress={() => setCooldown(value)} style={[s.cooldown,cooldown===value&&s.cooldownActive]}><Text style={[s.cooldownText,cooldown===value&&s.cooldownTextActive]}>{value} 分鐘</Text></TouchableOpacity>)}</View><Text style={s.section}>原生服務</Text><View style={s.statusCard}><View><Text style={s.appName}>無障礙服務</Text><Text style={s.statusText}>{status ? '已啟用' : '尚未啟用'}</Text></View><TouchableOpacity onPress={openAccessibility}><Text style={s.action}>前往開啟</Text></TouchableOpacity></View><TouchableOpacity onPress={save} style={s.save}><Text style={s.saveText}>儲存 App Lock 設定</Text></TouchableOpacity><Text style={s.notice}>僅 Android development build 支援。此功能使用 Android 無障礙服務偵測你選擇的受限 App；Android 系統設定內可隨時關閉該服務。</Text></ScrollView></SafeAreaView>;
}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:c.canvas},content:{padding:20,paddingBottom:110},eyebrow:{color:c.muted,fontSize:13,fontWeight:'800'},title:{color:c.ink,fontSize:30,fontWeight:'800',marginTop:4,marginBottom:22},hero:{padding:20,flexDirection:'row',alignItems:'center',backgroundColor:c.pale,borderRadius:8},heroCopy:{flex:1,paddingRight:14},heroTitle:{color:c.ink,fontSize:18,fontWeight:'800'},heroText:{color:c.muted,fontSize:14,lineHeight:20,marginTop:5},section:{color:c.ink,fontSize:18,fontWeight:'800',marginTop:30,marginBottom:12},appRow:{minHeight:64,padding:14,flexDirection:'row',alignItems:'center',backgroundColor:c.white,borderRadius:8,borderWidth:1,borderColor:c.border,marginBottom:8},checkbox:{width:24,height:24,borderRadius:5,borderWidth:2,borderColor:'#a8b0c2',alignItems:'center',justifyContent:'center',marginRight:14},checked:{backgroundColor:c.blue,borderColor:c.blue},tick:{color:c.white,fontWeight:'800'},appName:{color:c.ink,fontSize:15,fontWeight:'800'},package:{color:c.muted,fontSize:12,marginTop:3},fieldLabel:{color:c.ink,fontSize:14,fontWeight:'800',marginTop:14,marginBottom:8},input:{height:50,paddingHorizontal:14,color:c.ink,backgroundColor:c.white,borderWidth:1,borderColor:c.border,borderRadius:8,fontSize:15},cooldowns:{flexDirection:'row',gap:10},cooldown:{flex:1,height:46,alignItems:'center',justifyContent:'center',backgroundColor:c.white,borderWidth:1,borderColor:c.border,borderRadius:8},cooldownActive:{backgroundColor:c.pale,borderColor:c.blue},cooldownText:{color:c.muted,fontWeight:'800'},cooldownTextActive:{color:c.blue},statusCard:{padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:c.white,borderWidth:1,borderColor:c.border,borderRadius:8},statusText:{color:c.muted,fontSize:13,marginTop:4},action:{color:c.blue,fontWeight:'800'},save:{height:54,marginTop:28,alignItems:'center',justifyContent:'center',backgroundColor:c.blue,borderRadius:8,borderBottomWidth:4,borderBottomColor:c.blueDark},saveText:{color:c.white,fontSize:16,fontWeight:'800'},notice:{color:c.muted,fontSize:12,lineHeight:18,marginTop:16}});
