import { useMemo, useState } from 'react';
import { StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Card, recordStudyAttempt } from '@/db/queries';

export type QuizMode = 'choice' | 'write' | 'test';
export function QuizSession({ cards, mode, onFinish }: { cards: Card[]; mode: QuizMode; onFinish: () => void }) {
  const [index, setIndex] = useState(0); const [answer, setAnswer] = useState(''); const [checked, setChecked] = useState(false); const [correct, setCorrect] = useState(false);
  const card = cards[index]; const kind = mode === 'test' ? (index % 2 ? 'write' : 'choice') : mode;
  const options = useMemo(() => card ? [...cards.filter(x => x.id !== card.id).slice(0, 3).map(x => x.definition), card.definition].sort(() => Math.random() - .5) : [], [card?.id, cards]);
  if (!card) return <View style={s.empty}><Text style={s.muted}>這份單字本還沒有詞卡。</Text><TouchableOpacity onPress={onFinish}><Text style={s.link}>返回單字本</Text></TouchableOpacity></View>;
  const check = (value: string) => { if (checked) return; const result = kind === 'choice' ? value === card.definition : value.trim().toLowerCase() === card.word.toLowerCase(); setAnswer(value); setCorrect(result); setChecked(true); recordStudyAttempt(card.id, kind, result); };
  const next = () => { if (index === cards.length - 1) return onFinish(); setIndex(index + 1); setAnswer(''); setChecked(false); };
  return <View style={s.root}><View style={s.top}><Text style={s.muted}>{kind === 'choice' ? '選擇題' : '拼字練習'}</Text><Text style={s.count}>{index + 1} / {cards.length}</Text></View><View style={s.track}><View style={[s.fill,{width:`${(index+1)/cards.length*100}%`}]} /></View><View style={s.question}><Text style={s.prompt}>{kind === 'choice' ? card.word : card.definition}</Text><Text style={s.hint}>{kind === 'choice' ? '選出正確的中文釋義' : `請拼出 ${card.word.length} 個字母的英文單字`}</Text></View>{kind === 'choice' ? <View style={s.options}>{options.map(x => <TouchableOpacity key={x} onPress={() => check(x)} style={[s.option,checked && x===card.definition&&s.right,checked&&x===answer&&x!==card.definition&&s.wrong]}><Text style={s.optionText}>{x}</Text></TouchableOpacity>)}</View> : <View><TextInput style={s.input} value={answer} onChangeText={setAnswer} editable={!checked} autoCapitalize="none" placeholder="輸入英文單字" placeholderTextColor="#8a94ad"/>{!checked&&<TouchableOpacity onPress={() => check(answer)} disabled={!answer.trim()} style={[s.check,!answer.trim()&&s.disabled]}><Text style={s.white}>確認答案</Text></TouchableOpacity>}</View>}{checked&&<View style={[s.result,correct?s.resultRight:s.resultWrong]}><Text style={s.resultText}>{correct?'答對了':`正確答案：${card.word}`}</Text><TouchableOpacity onPress={next} style={s.next}><Text style={s.white}>{index===cards.length-1?'完成測驗':'下一題'}</Text></TouchableOpacity></View>}</View>;
}
const s=StyleSheet.create({root:{flex:1,padding:8},top:{flexDirection:'row',justifyContent:'space-between',marginBottom:10},muted:{color:'#586380',fontWeight:'800'},count:{color:'#1f2943',fontWeight:'800'},track:{height:8,borderRadius:99,overflow:'hidden',backgroundColor:'#dfe3ee'},fill:{height:'100%',backgroundColor:'#4255ff'},question:{marginTop:42,marginBottom:26,minHeight:170,padding:24,justifyContent:'center',backgroundColor:'#fff',borderRadius:8,borderWidth:1,borderColor:'#dfe3ee'},prompt:{color:'#1f2943',fontSize:30,fontWeight:'800',textAlign:'center'},hint:{color:'#66728f',fontSize:14,textAlign:'center',marginTop:14},options:{gap:10},option:{minHeight:54,paddingHorizontal:16,justifyContent:'center',backgroundColor:'#fff',borderRadius:8,borderWidth:1,borderBottomWidth:3,borderColor:'#dfe3ee'},optionText:{color:'#1f2943',fontSize:16,fontWeight:'700'},right:{backgroundColor:'#e1f7ed',borderColor:'#3bb273'},wrong:{backgroundColor:'#ffe8e9',borderColor:'#e85d75'},input:{height:56,paddingHorizontal:16,borderRadius:8,borderWidth:1,borderColor:'#dfe3ee',backgroundColor:'#fff',fontSize:17,color:'#1f2943'},check:{height:52,marginTop:12,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:'#4255ff',borderBottomWidth:4,borderBottomColor:'#2f3fca'},disabled:{opacity:.45},white:{color:'#fff',fontWeight:'800',fontSize:16},result:{marginTop:18,padding:16,borderRadius:8},resultRight:{backgroundColor:'#e1f7ed'},resultWrong:{backgroundColor:'#ffe8e9'},resultText:{color:'#1f2943',fontWeight:'800'},next:{height:48,marginTop:14,borderRadius:8,alignItems:'center',justifyContent:'center',backgroundColor:'#4255ff'},empty:{flex:1,alignItems:'center',justifyContent:'center',gap:16},link:{color:'#4255ff',fontWeight:'800'}});
